modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
    modId="cobblelifebestlife" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Cobble Life Best Life" #mandatory
    #updateJSONURL="http://myurl.me/" #optional
    #displayURL="http://example.com/" #optional
    #logoFile="examplemod.png" #optional
    #credits="" #optional
    authors="Lex" #optional
    description="A set of simple cobblestone generators. Mainly useful for servers that don't want multi-block cobblegens."
    
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
