modLoader="javafml"
loaderVersion="[47,)"
license="LGPL 2.1"

[[mods]]
    modId="cobblefordays"
    version="${file.jarVersion}"
    displayName="Cobble For Days"
    authors="Lex"
    description="A set of simple cobblestone generators. Mainly useful for servers that don't want multi-block cobblegens."
    
[[dependencies.cobblefordays]]
    modId="forge"
    mandatory=true
    versionRange="[52.0.9,)"
    ordering="NONE"
    side="BOTH"